import type { Brand, Category, StoreProduct } from "@/lib/types";

export const sampleBrands: Brand[] = [
  { id: "brand-ralph-lauren", name: "Ralph Lauren", slug: "ralph-lauren" },
  { id: "brand-calvin-klein", name: "Calvin Klein", slug: "calvin-klein" },
  { id: "brand-tommy", name: "Tommy Hilfiger", slug: "tommy-hilfiger" },
  { id: "brand-nike", name: "Nike", slug: "nike" },
  { id: "brand-adidas", name: "Adidas", slug: "adidas" },
  { id: "brand-levis", name: "Levi's", slug: "levis" },
  { id: "brand-lacoste", name: "Lacoste", slug: "lacoste" },
  { id: "brand-columbia", name: "Columbia", slug: "columbia" },
  { id: "brand-tnf", name: "The North Face", slug: "the-north-face" }
];

export const sampleCategories: Category[] = [
  { id: "cat-polos", name: "Polos", slug: "polos" },
  { id: "cat-camisas", name: "Camisas", slug: "camisas" },
  { id: "cat-casacas", name: "Casacas", slug: "casacas" },
  { id: "cat-poleras", name: "Poleras", slug: "poleras" },
  { id: "cat-hoodies", name: "Hoodies", slug: "hoodies" },
  { id: "cat-jeans", name: "Jeans", slug: "jeans" },
  { id: "cat-shorts", name: "Shorts", slug: "shorts" },
  { id: "cat-pantalones", name: "Pantalones", slug: "pantalones" },
  { id: "cat-accesorios", name: "Accesorios", slug: "accesorios" }
];

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;

export const sampleProducts: StoreProduct[] = [
  {
    id: "prod-001",
    name: "Camisa Oxford Ralph Lauren",
    slug: "camisa-oxford-ralph-lauren",
    description:
      "Camisa de algodon con corte clasico, ideal para looks casuales elevados. Seleccionada por su textura, color y excelente conservacion.",
    price: 169,
    salePrice: 149,
    brandId: "brand-ralph-lauren",
    categoryId: "cat-camisas",
    images: [
      img("photo-1598033129183-c4f50c736f10"),
      img("photo-1523398002811-999ca8dec234")
    ],
    size: "M",
    color: "Azul claro",
    gender: "hombre",
    condition: "excelente",
    measurements: { largo: "74 cm", pecho: "54 cm", hombros: "45 cm", manga: "64 cm" },
    observations: "Sin detalles visibles. Botones completos.",
    stock: 1,
    status: "disponible",
    isFeatured: true,
    isNewArrival: true,
    isUniquePiece: true,
    createdAt: "2026-05-01T12:00:00.000Z",
    brand: sampleBrands[0],
    category: sampleCategories[1]
  },
  {
    id: "prod-002",
    name: "Polo minimal Calvin Klein",
    slug: "polo-minimal-calvin-klein",
    description:
      "Polo basico premium con logo discreto. Una pieza versatil para combinar con denim, shorts o pantalones casuales.",
    price: 119,
    salePrice: null,
    brandId: "brand-calvin-klein",
    categoryId: "cat-polos",
    images: [img("photo-1521572163474-6864f9cf17ab"), img("photo-1586790170083-2f9ceadc732d")],
    size: "S",
    color: "Blanco",
    gender: "unisex",
    condition: "muy_bueno",
    measurements: { largo: "67 cm", pecho: "49 cm", hombros: "42 cm", manga: "20 cm" },
    observations: "Ligero uso natural en cuello, sin manchas.",
    stock: 1,
    status: "disponible",
    isFeatured: true,
    isNewArrival: false,
    isUniquePiece: true,
    createdAt: "2026-05-02T12:00:00.000Z",
    brand: sampleBrands[1],
    category: sampleCategories[0]
  },
  {
    id: "prod-003",
    name: "Jeans Levi's 501 vintage",
    slug: "jeans-levis-501-vintage",
    description:
      "Denim clasico de tiro medio con desgaste natural controlado. Pieza atemporal y resistente.",
    price: 199,
    salePrice: 179,
    brandId: "brand-levis",
    categoryId: "cat-jeans",
    images: [img("photo-1542272604-787c3835535d"), img("photo-1541099649105-f69ad21f3246")],
    size: "32",
    color: "Azul denim",
    gender: "hombre",
    condition: "muy_bueno",
    measurements: { largo: "104 cm", cintura: "82 cm" },
    observations: "Desgaste propio de denim vintage, sin roturas estructurales.",
    stock: 1,
    status: "disponible",
    isFeatured: true,
    isNewArrival: true,
    isUniquePiece: true,
    createdAt: "2026-05-03T12:00:00.000Z",
    brand: sampleBrands[5],
    category: sampleCategories[5]
  },
  {
    id: "prod-004",
    name: "Casaca Columbia ligera",
    slug: "casaca-columbia-ligera",
    description:
      "Casaca ligera para clima fresco, con bolsillos funcionales y acabado tecnico.",
    price: 229,
    salePrice: null,
    brandId: "brand-columbia",
    categoryId: "cat-casacas",
    images: [img("photo-1551028719-00167b16eac5"), img("photo-1548883354-7622d03aca27")],
    size: "L",
    color: "Verde oliva",
    gender: "unisex",
    condition: "excelente",
    measurements: { largo: "71 cm", pecho: "58 cm", hombros: "48 cm", manga: "66 cm" },
    observations: "Estado excelente. Cremalleras funcionando.",
    stock: 1,
    status: "disponible",
    isFeatured: false,
    isNewArrival: true,
    isUniquePiece: true,
    createdAt: "2026-05-04T12:00:00.000Z",
    brand: sampleBrands[7],
    category: sampleCategories[2]
  },
  {
    id: "prod-005",
    name: "Hoodie Nike Club",
    slug: "hoodie-nike-club",
    description:
      "Hoodie suave con fit relajado, seleccionado para uso diario con estilo limpio.",
    price: 189,
    salePrice: 159,
    brandId: "brand-nike",
    categoryId: "cat-hoodies",
    images: [img("photo-1515886657613-9f3515b0c78f"), img("photo-1556821840-3a63f95609a7")],
    size: "M",
    color: "Gris",
    gender: "unisex",
    condition: "bueno",
    measurements: { largo: "69 cm", pecho: "55 cm", hombros: "46 cm", manga: "63 cm" },
    observations: "Ligero desgaste en punos. Sin manchas visibles.",
    stock: 1,
    status: "disponible",
    isFeatured: false,
    isNewArrival: false,
    isUniquePiece: true,
    createdAt: "2026-05-05T12:00:00.000Z",
    brand: sampleBrands[3],
    category: sampleCategories[4]
  },
  {
    id: "prod-006",
    name: "Polo Lacoste piqué",
    slug: "polo-lacoste-pique",
    description:
      "Polo piqué de estilo atemporal, con textura firme y presencia de boutique.",
    price: 179,
    salePrice: null,
    brandId: "brand-lacoste",
    categoryId: "cat-polos",
    images: [img("photo-1523381294911-8d3cead13475"), img("photo-1503341455253-b2e723bb3dbb")],
    size: "M",
    color: "Crema",
    gender: "hombre",
    condition: "excelente",
    measurements: { largo: "70 cm", pecho: "52 cm", hombros: "44 cm", manga: "22 cm" },
    observations: "Sin detalles visibles.",
    stock: 1,
    status: "disponible",
    isFeatured: true,
    isNewArrival: false,
    isUniquePiece: true,
    createdAt: "2026-05-06T12:00:00.000Z",
    brand: sampleBrands[6],
    category: sampleCategories[0]
  }
];
